name: testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  configure:
    # configures version and output from version_map.json using scripts/version_outptu_actions.py and otuptus as github_output
    # uses GITHub_outouput ans matrix to run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "mk-math[dev]"

      - name: Configure
        run: |
          python scripts/version_output_actions.py


  test:
    # runs test using the version and output from version_map.json
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.github_output) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "mk-math[dev]"

      - name: Test with ${{ matrix.version }}
        run: |
          pytest tests
